### ISSUE TITLE
Display Your Collection With Metadata Info

### ISSUE THREAD

**Issue by Harandi6135** [Gravity-Spy/gravityspytools#12]
After selecting some subjects and creating a new collection, I clicked on the title of the page which is:
Collection Similar to 6065653 Created By User Mabi ID AXpQW (24)
BY SBC538
and copied the last segment of the URL and pasted in the textbox to get the metadata info of the collection but got the following error: 
Not Found page
The requested URL /collectioninfo/collectioninfo/ was not found on this server.
I checked with the name of the new collection that I made based on the search result and got the same error.

**Comment by scottcoughlin2014** [comment]
Thank for the Issue @Harandi6135! I was able to easily identify the problem based on your description.

See: https://github.com/Gravity-Spy/gravityspytools/commit/5c62db36a2de4a547b6bef39e111b5196f8ec036
