### ISSUE TITLE
Instructions for the similarity search

### ISSUE THREAD

**Issue by crowston** [Gravity-Spy/gravityspytools#3]
Could you add a sentence or two explaining what the search page does? Things like, what the search does, how many images is it reasonable to search for, where to find the Zooniverse assigned random ID or the GravitySpy uniqueid, whether you need both or just one, whether you should preview or create a collection, and where to find the collection.

**Comment by scottcoughlin2014** [comment]
I have created an About page place holder where either a GIF or a Screen Shot Hot-To will live
https://github.com/Gravity-Spy/gravityspytools/commit/b89700777320e29a5733a7928e35eb9e1d2ca212

https://gravityspytools.ciera.northwestern.edu/about/

**Comment by scottcoughlin2014** [comment]
Alright I made a video and got it embedded such that it is easy to see in Google Chrome and Firefox at the least.

https://gravityspytools.ciera.northwestern.edu/about/

https://github.com/Gravity-Spy/gravityspytools/commit/0847f4ced510ed0aec3c890d72215051f3f1a1ee

Closing for now so we can open a separate issue under which improvements to the previously non existent about page can go
