### ISSUE TITLE
Glitch Search: List of IDs functionality

### ISSUE THREAD

**Issue by mzevin1** [Gravity-Spy/gravityspytools#7]
Allow the searching of many glitches from a list of IDs (i.e., one Gravity Spy ID per line, or a csv file of all the glitches...)

**Comment by scottcoughlin2014** [comment]
PR #8 Should address this need albeit in a short term janky way. In long run LDVW will need to have this capability.

https://gravityspytools.ciera.northwestern.edu/display_glitches_DB/

**Comment by scottcoughlin2014** [comment]
I am going to consider this closed until further notice.
